import styles from "./style";
import React, {useEffect, useRef, useState} from 'react'
import { useFormik } from "formik";
import { motion as m } from "framer-motion";
import Navbar from "./Navbar";
import Hero from "./Hero";

export default function Home() {
  
  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full"
    >
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className="  bg-blue-gradient w-full overflow-hidden">
        <div className={`${styles.paddingX} ${styles.flexCenter}`}>
          <div className={`${styles.boxWidth}`}>
            <Navbar />
          </div>
        </div>

        <div className={` ${styles.flexStart} shadow-md border-solid bottom-1 justify-center items-center  bg-wh-700`}>
          <div className={`${styles.boxWidth} shadow-md md:w-1/2 w-full bg-white md:mt-6`}>
            <Hero className="bg-white " />
          </div>
        </div>
        
      </main>
    </m.div>
  );
}
